// 知名平台域名白名单：命中后提供权威品牌名与默认分类
// 用于 analyzePageType 的页面类型分析，独立出文件便于维护与社区扩展
module.exports = {
  // 代码托管
  'github.com': { brand: 'GitHub', defaultCategory: 'code' },
  'gitlab.com': { brand: 'GitLab', defaultCategory: 'code' },
  'gitee.com': { brand: 'Gitee', defaultCategory: 'code' },
  'bitbucket.org': { brand: 'Bitbucket', defaultCategory: 'code' },
  'codeberg.org': { brand: 'Codeberg', defaultCategory: 'code' },
  // 云服务与部署
  'vercel.com': { brand: 'Vercel', defaultCategory: 'deploy' },
  'netlify.com': { brand: 'Netlify', defaultCategory: 'deploy' },
  'heroku.com': { brand: 'Heroku', defaultCategory: 'deploy' },
  'railway.app': { brand: 'Railway', defaultCategory: 'deploy' },
  'render.com': { brand: 'Render', defaultCategory: 'deploy' },
  'fly.io': { brand: 'Fly.io', defaultCategory: 'deploy' },
  'aws.amazon.com': { brand: 'AWS', defaultCategory: 'cloud' },
  'cloud.google.com': { brand: 'Google Cloud', defaultCategory: 'cloud' },
  'azure.microsoft.com': { brand: 'Azure', defaultCategory: 'cloud' },
  'cloudflare.com': { brand: 'Cloudflare', defaultCategory: 'network' },
  // 数据库
  'supabase.com': { brand: 'Supabase', defaultCategory: 'database' },
  'firebase.google.com': { brand: 'Firebase', defaultCategory: 'database' },
  'planetscale.com': { brand: 'PlanetScale', defaultCategory: 'database' },
  'mongodb.com': { brand: 'MongoDB', defaultCategory: 'database' },
  'neon.tech': { brand: 'Neon', defaultCategory: 'database' },
  // 设计工具
  'figma.com': { brand: 'Figma', defaultCategory: 'design' },
  'canva.com': { brand: 'Canva', defaultCategory: 'design' },
  'sketch.com': { brand: 'Sketch', defaultCategory: 'design' },
  'dribbble.com': { brand: 'Dribbble', defaultCategory: 'design' },
  'behance.net': { brand: 'Behance', defaultCategory: 'design' },
  // 生产力工具
  'notion.so': { brand: 'Notion', defaultCategory: 'productivity' },
  'airtable.com': { brand: 'Airtable', defaultCategory: 'productivity' },
  'coda.io': { brand: 'Coda', defaultCategory: 'productivity' },
  'clickup.com': { brand: 'ClickUp', defaultCategory: 'productivity' },
  'monday.com': { brand: 'Monday', defaultCategory: 'productivity' },
  'trello.com': { brand: 'Trello', defaultCategory: 'productivity' },
  'asana.com': { brand: 'Asana', defaultCategory: 'productivity' },
  'linear.app': { brand: 'Linear', defaultCategory: 'productivity' },
  // 搜索与AI
  'google.com': { brand: 'Google', defaultCategory: 'search' },
  'bing.com': { brand: 'Bing', defaultCategory: 'search' },
  'baidu.com': { brand: '百度', defaultCategory: 'search' },
  'openai.com': { brand: 'OpenAI', defaultCategory: 'ai' },
  'anthropic.com': { brand: 'Anthropic', defaultCategory: 'ai' },
  'gemini.google': { brand: 'Gemini', defaultCategory: 'ai' },
  'claude.ai': { brand: 'Claude', defaultCategory: 'ai' },
  'chat.openai.com': { brand: 'ChatGPT', defaultCategory: 'ai' },
  'huggingface.co': { brand: 'Hugging Face', defaultCategory: 'ai' },
  'midjourney.com': { brand: 'Midjourney', defaultCategory: 'ai' },
  'stability.ai': { brand: 'Stability AI', defaultCategory: 'ai' },
  // 视频平台
  'youtube.com': { brand: 'YouTube', defaultCategory: 'video' },
  'bilibili.com': { brand: '哔哩哔哩', defaultCategory: 'video' },
  'vimeo.com': { brand: 'Vimeo', defaultCategory: 'video' },
  'twitch.tv': { brand: 'Twitch', defaultCategory: 'video' },
  'douyin.com': { brand: '抖音', defaultCategory: 'video' },
  'ixigua.com': { brand: '西瓜视频', defaultCategory: 'video' },
  // 社交平台
  'twitter.com': { brand: 'Twitter', defaultCategory: 'social' },
  'x.com': { brand: 'X', defaultCategory: 'social' },
  'linkedin.com': { brand: 'LinkedIn', defaultCategory: 'social' },
  'facebook.com': { brand: 'Facebook', defaultCategory: 'social' },
  'instagram.com': { brand: 'Instagram', defaultCategory: 'social' },
  'tiktok.com': { brand: 'TikTok', defaultCategory: 'social' },
  'weibo.com': { brand: '微博', defaultCategory: 'social' },
  'xiaohongshu.com': { brand: '小红书', defaultCategory: 'social' },
  // 论坛与问答
  'reddit.com': { brand: 'Reddit', defaultCategory: 'forum' },
  'zhihu.com': { brand: '知乎', defaultCategory: 'qa' },
  'quora.com': { brand: 'Quora', defaultCategory: 'qa' },
  'stackoverflow.com': { brand: 'Stack Overflow', defaultCategory: 'tech-qa' },
  'segmentfault.com': { brand: 'SegmentFault', defaultCategory: 'tech-qa' },
  'v2ex.com': { brand: 'V2EX', defaultCategory: 'tech-forum' },
  // 博客与内容
  'medium.com': { brand: 'Medium', defaultCategory: 'blog' },
  'dev.to': { brand: 'DEV Community', defaultCategory: 'tech-blog' },
  'hashnode.dev': { brand: 'Hashnode', defaultCategory: 'tech-blog' },
  'juejin.cn': { brand: '掘金', defaultCategory: 'tech-blog' },
  'csdn.net': { brand: 'CSDN', defaultCategory: 'tech-blog' },
  'cnblogs.com': { brand: '博客园', defaultCategory: 'tech-blog' },
  'jianshu.com': { brand: '简书', defaultCategory: 'blog' },
  'substack.com': { brand: 'Substack', defaultCategory: 'newsletter' },
  // 沟通协作
  'discord.com': { brand: 'Discord', defaultCategory: 'community' },
  'slack.com': { brand: 'Slack', defaultCategory: 'communication' },
  'telegram.org': { brand: 'Telegram', defaultCategory: 'communication' },
  'zoom.us': { brand: 'Zoom', defaultCategory: 'communication' },
  'teams.microsoft.com': { brand: 'Microsoft Teams', defaultCategory: 'communication' },
  'feishu.cn': { brand: '飞书', defaultCategory: 'communication' },
  'dingtalk.com': { brand: '钉钉', defaultCategory: 'communication' },
  'weixin.qq.com': { brand: '微信', defaultCategory: 'communication' },
  // 包管理
  'npmjs.com': { brand: 'npm', defaultCategory: 'package' },
  'pypi.org': { brand: 'PyPI', defaultCategory: 'package' },
  'crates.io': { brand: 'crates.io', defaultCategory: 'package' },
  'pkg.go.dev': { brand: 'Go Packages', defaultCategory: 'package' },
  'rubygems.org': { brand: 'RubyGems', defaultCategory: 'package' },
  'packagist.org': { brand: 'Packagist', defaultCategory: 'package' },
  'mvnrepository.com': { brand: 'Maven', defaultCategory: 'package' },
  // 电商
  'amazon.com': { brand: 'Amazon', defaultCategory: 'ecommerce' },
  'ebay.com': { brand: 'eBay', defaultCategory: 'ecommerce' },
  'taobao.com': { brand: '淘宝', defaultCategory: 'ecommerce' },
  'jd.com': { brand: '京东', defaultCategory: 'ecommerce' },
  'pinduoduo.com': { brand: '拼多多', defaultCategory: 'ecommerce' },
  'shopify.com': { brand: 'Shopify', defaultCategory: 'ecommerce' },
  // 科技巨头
  'microsoft.com': { brand: 'Microsoft', defaultCategory: 'tech' },
  'apple.com': { brand: 'Apple', defaultCategory: 'tech' },
  'mozilla.org': { brand: 'Mozilla', defaultCategory: 'tech' },
  // 文档与知识库
  'readthedocs.io': { brand: 'Read the Docs', defaultCategory: 'docs' },
  'gitbook.io': { brand: 'GitBook', defaultCategory: 'docs' },
  'docsify.js.org': { brand: 'Docsify', defaultCategory: 'docs' },
  'docusaurus.io': { brand: 'Docusaurus', defaultCategory: 'docs' },
  'vuepress.vuejs.org': { brand: 'VuePress', defaultCategory: 'docs' }
};